name: Deploy Site
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100' # SDK Version to use.
    - run: dotnet run --project Vike.Blog -- deploy -l debug
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
